services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: loja-virtual
      POSTGRES_PASSWORD: 1231lalk1lnals344#$%
      POSTGRES_DB: loja-virtual
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - .docker/redis/data:/data
